// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/basmah-redesign/BoldVariant.tsx": () => import("../components/mockups/basmah-redesign/BoldVariant.tsx"),
  "./components/mockups/basmah-redesign/GlassVariant.tsx": () => import("../components/mockups/basmah-redesign/GlassVariant.tsx"),
  "./components/mockups/basmah-redesign/StreetVariant.tsx": () => import("../components/mockups/basmah-redesign/StreetVariant.tsx")
};
